version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "mbswappdeployartifacts"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
        # Download and Install NodeJS 8.0     
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - echo Installing source NPM dependencies...
        # Install http drivers for node
        - sudo apt-get update -y
        - sudo apt-get install -y apt-transport-https
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes